;/*FB_PKG_DELIM*/

__d("BaseMultiPageEntryPointImpl.react",["CometPlaceholder.react","CometRelay","clearTimeout","react","setTimeout"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;var j=b.useEffect,k=b.useRef;function a(a){var b=a.entryPoint,e=a.environmentProvider,f=a.fallback,g=a.loadedEntryPoint,h=a.otherProps,l=a.placeholderComponent;l=l===void 0?c("CometPlaceholder.react"):l;var m=a.preloadParams;a=a.usePlaceholder;a=a===void 0?!0:a;e=d("CometRelay").useEntryPointLoader(e,b);var n=e[0],o=e[1],p=e[2],q=(b=n)!=null?b:g,r=k(null);j(function(){r.current!=null&&(c("clearTimeout")(r.current),r.current=null);q.isDisposed&&o(m);return function(){r.current=c("setTimeout")(function(){n?p():g.dispose(),r.current=null},6e4)}},[p,q.isDisposed,g,m,o,n]);e=i.jsx(d("CometRelay").EntryPointContainer,{entryPointReference:q,props:h});return!a?e:i.jsx(l,{fallback:f,children:e})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("PolarisActivityFeedFollowRequestsViewQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7150474615053602"}),null);
__d("PolarisActivityFeedFollowRequestsViewQuery$Parameters",["PolarisActivityFeedFollowRequestsViewQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisActivityFeedFollowRequestsViewQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisActivityFeedFollowRequestsViewQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisActivityFeedMediaLikersListViewQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7944665242252272"}),null);
__d("PolarisActivityFeedMediaLikersListViewQuery$Parameters",["PolarisActivityFeedMediaLikersListViewQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisActivityFeedMediaLikersListViewQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisActivityFeedMediaLikersListViewQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisActivityFeedSecurityAlertsDataDefault.react",["react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||(h=d("react"))).c;h;var j=[];function a(a){var b=i(2);a=a.children;var c;b[0]!==a?(c=a(j),b[0]=a,b[1]=c):c=b[1];return c}g["default"]=a}),98);
__d("PolarisActivityFeedV2FollowRequests.entrypoint",["JSResourceForInteraction","PolarisActivityFeedFollowRequestsViewQuery$Parameters","PolarisSuggestedUserListQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{PolarisActivityFollowRequestsViewQuery:{options:{fetchPolicy:"network-only"},parameters:c("PolarisActivityFeedFollowRequestsViewQuery$Parameters"),variables:{_request_data:{},first:10}},PolarisSuggestedUserListQuery:{options:{},parameters:c("PolarisSuggestedUserListQuery$Parameters"),variables:{data:{max_number_to_display:30,module:"discover_people"}}}}}},root:c("JSResourceForInteraction")("PolarisActivityFeedV2FollowRequests.react").__setRef("PolarisActivityFeedV2FollowRequests.entrypoint")};g["default"]=a}),98);
__d("PolarisActivityFeedV2MediaLikers.entrypoint",["JSResourceForInteraction","PolarisActivityFeedMediaLikersListViewQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.routeParams.media_id;return a==null?{}:{queries:{PolarisActivityFeedMediaLikersListViewQuery:{options:{},parameters:c("PolarisActivityFeedMediaLikersListViewQuery$Parameters"),variables:{include_follower_count:!1,media_id:a}}}}},root:c("JSResourceForInteraction")("PolarisActivityFeedV2MediaLikers.react").__setRef("PolarisActivityFeedV2MediaLikers.entrypoint")};g["default"]=a}),98);
__d("PolarisActivityFeedV2DesktopRoot.entrypoint",["JSResourceForInteraction","NestedRelayEntryPointBuilderUtils","PolarisActivityFeedV2FollowRequests.entrypoint","PolarisActivityFeedV2MediaLikers.entrypoint","PolarisActivityFeedV2Stories.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{entryPoints:{content:h(a)}}},root:c("JSResourceForInteraction")("PolarisActivityFeedV2DesktopRoot.react").__setRef("PolarisActivityFeedV2DesktopRoot.entrypoint")};function h(a){var c=a.routeParams.followRequests===!0,e=a.routeParams.media_id;if(c)return d("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:b("PolarisActivityFeedV2FollowRequests.entrypoint"),entryPointParams:a});else if(e!=null)return d("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:b("PolarisActivityFeedV2MediaLikers.entrypoint"),entryPointParams:{routeParams:{media_id:e},routeProps:{}}});return d("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:b("PolarisActivityFeedV2Stories.entrypoint"),entryPointParams:a})}g["default"]=a}),98);
__d("XPolarisPostControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/{permalink_key}/{shortcode}/",Object.freeze({chaining:!1,viewer:!1,show_insights:!1}),void 0);b=a;g["default"]=b}),98);